# Logfile created on 2014-03-12 11:58:17 -0700 by logger.rb/44203
I, [2014-03-12T11:58:17.008109 #31099]  INFO -- : *** Below you'll find the most recent exception thrown, this will likely (but not certainly) be the exception that made your application exit abnormally ***
E, [2014-03-12T11:58:17.008155 #31099] ERROR -- : Error connecting to Redis on localhost:1234 (ECONNREFUSED) (Redis::CannotConnectError)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:290:in `rescue in establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
I, [2014-03-12T11:58:17.008212 #31099]  INFO -- : *** Below you'll find all the exception objects in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2014-03-12T11:58:17.011205 #31099] ERROR -- : stream closed (IOError)

E, [2014-03-12T11:58:17.011353 #31099] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2014-03-12T11:58:17.011398 #31099] ERROR -- : stack level too deep (SystemStackError)

E, [2014-03-12T11:58:17.011545 #31099] ERROR -- : exception reentered (fatal)

E, [2014-03-12T11:58:17.012514 #31099] ERROR -- : No such file or directory @ rb_sysopen - /Users/jasonkriss/Developer/hybrid_projects/daemon-example/log/backtrace-20140312115817-31099.log (Errno::ENOENT)
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `initialize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `new'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/safely-0.3.2/lib/safely/backtrace.rb:24:in `new'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/safely-0.3.2/lib/safely/backtrace.rb:24:in `log_exceptions'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/safely-0.3.2/lib/safely/backtrace.rb:10:in `block in enable!'
E, [2014-03-12T11:58:17.013115 #31099] ERROR -- : Error connecting to Redis on localhost:1234 (ECONNREFUSED) (Redis::CannotConnectError)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:290:in `rescue in establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013160 #31099] ERROR -- : Connection refused - connect(2) for [fe80::1%lo0]:1234 (Errno::ECONNREFUSED)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129:in `connect_nonblock'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129:in `rescue in connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:121:in `connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013204 #31099] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013281 #31099] ERROR -- : Connection refused - connect(2) for [::1]:1234 (Errno::ECONNREFUSED)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129:in `connect_nonblock'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129:in `rescue in connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:121:in `connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013346 #31099] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013413 #31099] ERROR -- : Connection refused - connect(2) for 127.0.0.1:1234 (Errno::ECONNREFUSED)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129:in `connect_nonblock'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:129:in `rescue in connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:121:in `connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013482 #31099] ERROR -- : Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_nonblock'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:122:in `connect_addrinfo'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:162:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `each_with_index'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:160:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:79:in `block in connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:304:in `ensure_connected'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:613:in `block in incr'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/Users/jasonkriss/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/redis-3.0.7/lib/redis.rb:612:in `incr'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:9:in `block in <top (required)>'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `loop'
/Users/jasonkriss/Developer/hybrid_projects/daemon-example/libexec/daemon-example-daemon.rb:8:in `<top (required)>'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `require'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:38:in `run'
/Users/jasonkriss/.rvm/gems/ruby-2.1.1/gems/daemon-kit-0.2.3/lib/daemon_kit/application.rb:21:in `exec'
bin/daemon-example:8:in `<main>'
E, [2014-03-12T11:58:17.013847 #31099] ERROR -- : Value will be available once the pipeline executes. (Redis::FutureNotReady)

